class HomePage:
    # VUSEWORLD = '/XCUIElementTypeStaticText[@name="Vuseworld"]'
    VUSEWORLD = 'Vuseworld'
    FIRST_DEVICE ='//XCUIElementTypeOther[@name="MYVUSE"]/XCUIElementTypeOther[10]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[3]/XCUIElementTypeLink'
    SLIDE_1 = '//XCUIElementTypeButton[@name="1 of 7"]'
    SLIDE_2 = '//XCUIElementTypeButton[@name="2 of 7"]'
    SLIDE_3 = '//XCUIElementTypeButton[@name="3 of 7"]'
    SLIDE_4 = '//XCUIElementTypeButton[@name="4 of 7"]'
    SLIDE_5 = '//XCUIElementTypeButton[@name="5 of 7"]'
    SLIDE_6 = '//XCUIElementTypeButton[@name="6 of 7"]'
    SLIDE_7 = '//XCUIElementTypeButton[@name="7 of 7"]'
    CLOSE_DEVICE = '//XCUIElementTypeLink[@x="372"]'
    MORE_PAGE = '//XCUIElementTypeImage[@name="More"]'
    ACCOUNT_DETAILS = '/XCUIElementTypeStaticText[@name="ACCOUNT"]'
    DEVICE_DETAILS = '//XCUIElementTypeImage[@name="Device"]'
